logo_title: 谦益

style: black

favicon: /blog/favicon.ico

menu:
  博客: /
  作品: /project
  关于: /about
  Github: https://github.com/wilsonyiyi

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false
